config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
resources :onsens
  root 'onsens#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/onsen.rb
class Onsen < ApplicationRecord
  acts_as_taggable
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/onsens_controller.rb
class OnsensController < ApplicationController

  before_action :authenticate_user!

  def index
    @onsens = Onsen.all
    if params[:tag_name]
      @onsens = Onsen.tagged_with("#{params[:tag_name]}")
    end
end

  def new
    @onsen = Onsen.new
  end

  def create
    onsen = Onsen.new(onsen_params)
    if onsen.save!
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end

  def show
    @onsen = Onsen.find(params[:id])
  end

  def edit
    @onsen = Onsen.find(params[:id])
  end

  def update
    onsen = Onsen.find(params[:id])
    if onsen.update(onsen_params)
      redirect_to :action => "show", :id => onsen.id
    else
      redirect_to :action => "new"
    end
  end
  
  def destroy
    onsen = Onsen.find(params[:id])
    onsen.destroy
    redirect_to action: :index
  end

  private
  def onsen_params
    params.require(:onsen).permit(:onsen_name, :onsen_time, :onsen_day, :onsen_tel, :onsen_adress, :onsen_hp, :price, :spa_data, :equipment, :features, :reviews, :tag_list, :overall, :level)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/onsens_helper.rb
module OnsensHelper
  def getPercent(number) 
    if number.present?
      calPercent = number/5.to_f * 100
      # calPercent = number/10.to_f * 100

      percent = calPercent.round

      return percent.to_s
   else
     return 0
   end
 end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yutatwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/onsens/_tag_list.html.erb
<% tag_list.each do |tag| %>
<%= link_to tag, onsens_path(tag_name: tag) %>
<% end %>

app/views/onsens/edit.html.erb
<h1>温泉サイト</h1>
<h3>新規温泉施設</h3>
<%= form_for @onsen do |f| %>

<div class="field">
    <%= f.label :"施設名" %>
    <%= f.text_field :onsen_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"住所" %>
    <%= f.text_field :onsen_adress, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :tel, :"TEL" %>
    <%= f.text_field :onsen_tel, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"営業時間" %>
    <%= f.text_field :onsen_time, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"定休日" %>
    <%= f.text_field :onsen_day, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :hp, :"公式HP" %>
    <%= f.text_field :onsen_hp, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"料金" %>
    <%= f.text_field :price, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"設備"  %>
    <%= f.select :spa_data, 
    [["露天風呂", "露天風呂"], 
    ["岩盤浴", "岩盤浴"], 
    ["サウナ", "サウナ"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :"アメニティ"  %>
    <%= f.select :equipment, 
    [["シャンプー等", "シャンプー等"], 
    ["休憩所", "休憩所"], 
    ["食事", "食事"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :"特徴" %>
    <%= f.text_field :features, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"口コミ" %>
    <%= f.text_area :reviews, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :タグ %>
    <%= f.text_field :tag_list, value: @onsen.tag_list %>
　　</div>

<h5>総合評価</h5>
   <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
 </div>

<h5>温泉の効能レベル</h5>
  <div class="post_form">
    <%= f.radio_button :level,  5 ,id: 'star6'%>
    <label for="star6"><span class="text">難しい</span>★</label>

    <%= f.radio_button :level,  4 ,id: 'star7'%>
    <label for="star7"><span class="text">やや難しい</span>★</label>

    <%= f.radio_button :level, 3 ,id: 'star8'%>
    <label for="star8"><span class="text">普通</span>★</label>

    <%= f.radio_button :level , 2 ,id: 'star9'%>
    <label for="star9"><span class="text">やや簡単</span>★</label>

    <%= f.radio_button :level , 1 ,id: 'star10'%>
    <label for="star10"><span class="text">簡単</span>★</label>
 </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", onsens_path %>

app/views/onsens/index.html.erb
<h1>温泉サイト</h1>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %> 

<%= link_to "ログイン", onsens_path %>
<%= link_to "新規登録", new_user_registration_path %>

<h3>温泉施設一覧</h3>
<%= link_to "新規投稿へ", new_onsen_path %>
<div class="onsens-container">
  <% @onsens.each do |t| %>
    <div class="onsen">
      <div>
      施設名:
      <%= t.onsen_name %>
    </div>

    <div>
      住所:
      <%= t.onsen_adress%>
      </div>
      
      <div>
      TEL:
      <%= t.onsen_tel %>
      </div>

      <div>
      営業時間:
      <%= t.onsen_time %>
      </div>

      <div>
      定休日:
      <%= t.onsen_day %>
      </div>

      <div>
      公式HP:
      <%= t.onsen_hp%>
      </div>

      <div>
      料金:
      <%= t.price %>
      </div>

      <div>
      設備:
      <%= t.spa_data %>
      </div>

      <div>
      アメニティ:
      <%= t.equipment %>
      </div>

      <div>
      特徴:
      <%= t.features %>
      </div>

      <div>
      口コミ:
      <%= t.reviews %>
      </div>

<%= render 'onsens/tag_list', tag_list: t.tag_list %>

    <div>
<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.overall) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>

<div>
<h2>温泉の効能レベル：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(t.level) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span>
</h2>
</div>

<div>
        投稿日時:
      <%= t.created_at %>
      </div>
    </div>

<%= link_to "投稿詳細へ", onsen_path(t.id) %> 
<%= link_to "編集する", edit_onsen_path(t.id) %>
<%= button_to "削除する", onsen_path(t.id), method: :delete %>
  <% end %>
</div>

app/views/onsens/new.html.erb
<h1>温泉サイト</h1>
<h3>新規温泉施設</h3>
<%= form_for @onsen do |f| %>

<div class="field">
    <%= f.label :"施設名" %>
    <%= f.text_field :onsen_name, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"住所" %>
    <%= f.text_field :onsen_adress, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :tel, :"TEL" %>
    <%= f.text_field :onsen_tel, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"営業時間" %>
    <%= f.text_field :onsen_time, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"定休日" %>
    <%= f.text_field :onsen_day, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :hp, :"公式HP" %>
    <%= f.text_field :onsen_hp, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"料金" %>
    <%= f.text_field :price, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"設備"  %>
    <%= f.select :spa_data, 
    [["露天風呂", "露天風呂"], 
    ["岩盤浴", "岩盤浴"], 
    ["サウナ", "サウナ"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :"アメニティ"  %>
    <%= f.select :equipment, 
    [["シャンプー等", "シャンプー等"], 
    ["休憩所", "休憩所"], 
    ["食事", "食事"]], include_blank: "選択して下さい" %>
  </div>

  <div class="field">
    <%= f.label :"特徴" %>
    <%= f.text_field :features, :size => 30 %>
  </div>

  <div class="field">
    <%= f.label :"口コミ" %>
    <%= f.text_area :reviews, :size => "30x2" %>
  </div>

  <div class="field">
    <%= f.label :タグ %>
    <%= f.text_field :tag_list, value: @onsen.tag_list %>
　　</div>

<h5>総合評価</h5>
   <div class="post_form">
    <%= f.radio_button :overall, 5 ,id: 'star1'%>
    <label for="star1"><span class="text">最高</span>★</label>

    <%= f.radio_button :overall, 4 ,id: 'star2'%>
    <label for="star2"><span class="text">良い</span>★</label>

    <%= f.radio_button :overall, 3 ,id: 'star3'%>
    <label for="star3"><span class="text">普通</span>★</label>

    <%= f.radio_button :overall, 2 ,id: 'star4'%>
    <label for="star4"><span class="text">悪い</span>★</label>

    <%= f.radio_button :overall, 1 ,id: 'star5'%>
    <label for="star5"><span class="text">最悪</span>★</label>
 </div>

<h5>温泉の効能レベル</h5>
  <div class="post_form">
    <%= f.radio_button :level,  5 ,id: 'star6'%>
    <label for="star6"><span class="text">難しい</span>★</label>

    <%= f.radio_button :level,  4 ,id: 'star7'%>
    <label for="star7"><span class="text">やや難しい</span>★</label>

    <%= f.radio_button :level, 3 ,id: 'star8'%>
    <label for="star8"><span class="text">普通</span>★</label>

    <%= f.radio_button :level , 2 ,id: 'star9'%>
    <label for="star9"><span class="text">やや簡単</span>★</label>

    <%= f.radio_button :level , 1 ,id: 'star10'%>
    <label for="star10"><span class="text">簡単</span>★</label>
 </div>

  <%= f.submit "投稿する" %>
<% end %>

<%= link_to "一覧に戻る", onsens_path %>

app/views/onsens/show.html.erb
<h1>温泉サイト</h1>
<h3>温泉投稿詳細</h3>
<div class="onsen">
  <p>
    <div>
      施設名:
      <%= @onsen.onsen_name %>
    </div>

    <div>
      住所:
      <%= @onsen.onsen_adress%>
      </div>
      
      <div>
      TEL:
      <%= @onsen.onsen_tel %>
      </div>

      <div>
      営業時間:
      <%= @onsen.onsen_time %>
      </div>

      <div>
      定休日:
      <%= @onsen.onsen_day %>
      </div>

      <div>
      公式HP:
      <%= @onsen.onsen_hp%>
      </div>

      <div>
      料金:
      <%= @onsen.price %>
      </div>

      <div>
      設備:
      <%= @onsen.spa_data %>
      </div>

      <div>
      アメニティ:
      <%= @onsen.equipment %>
      </div>

      <div>
      特徴:
      <%= @onsen.features %>
      </div>

      <div>
      口コミ:
      <%= @onsen.reviews %>
      </div>

<%= render 'onsens/tag_list', tag_list: @onsen.tag_list %>
    </p>

    <div>
<h2>総合評価：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(@onsen.overall) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span> 
</h2>
</div>

<div>
<h2>温泉の効能レベル：
<span class="star-rating">
   <span class="star-rating-front" style="width: <%= getPercent(@onsen.level) %>%;">★★★★★</span>
   <span class="star-rating-back">★★★★★</span>
</span>
</h2>
</div>

<p>
    <div>
        投稿日時:
    <%= @onsen.created_at %>
    </div>
    </p>

</div>

<%= link_to "編集する", edit_onsen_path(@onsen.id) %>
<%= link_to "投稿一覧に戻る", onsens_path %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>